apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s7vgawvz9-java-quarkus
  janus-idp.io/tekton: s7vgawvz9-java-quarkus
  backstage.io/kubernetes-id: s7vgawvz9-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s7vgawvz9-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
