apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: s7vgawvz9-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/s7vgawvz9-java-quarkus-gitops